FROM eclipse-temurin:17-jdk-jammy

# Instalar dependencias
RUN apt-get update && apt-get install -y \
    curl wget python3 python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Instalar Spark 4.1.1
RUN wget -q https://archive.apache.org/dist/spark/spark-4.1.1/spark-4.1.1-bin-hadoop3.tgz \
    && tar -xzf spark-4.1.1-bin-hadoop3.tgz -C /opt \
    && mv /opt/spark-4.1.1-bin-hadoop3 /opt/spark \
    && rm spark-4.1.1-bin-hadoop3.tgz

# Eliminar JARs S3A que puedan causar conflictos
RUN rm -f /opt/spark/jars/hadoop-aws-*.jar \
    && rm -f /opt/spark/jars/aws-java-sdk-bundle-*.jar \
    && rm -f /opt/spark/jars/bundle-*.jar

# Versión compatible: hadoop-aws 3.3.4 + aws-sdk 1.12.262
RUN wget -q https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar \
    -O /opt/spark/jars/hadoop-aws-3.3.4.jar && \
    wget -q https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar \
    -O /opt/spark/jars/aws-java-sdk-bundle-1.12.262.jar

#Instalación mlFlow
RUN pip3 install numpy findspark mlflow

# Variables de entorno
ENV SPARK_HOME=/opt/spark
ENV PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin
ENV JAVA_HOME=/opt/java/openjdk

# Python para PySpark + dependencias necesarias
RUN pip3 install numpy findspark

# Scripts de arranque
COPY dockerfiles/start-master.sh /start-master.sh
COPY dockerfiles/start-worker.sh /start-worker.sh
RUN chmod +x /start-master.sh /start-worker.sh

COPY dockerfiles/spark-defaults.conf /opt/spark/conf/spark-defaults.conf

WORKDIR /opt/spark